__default__:
  h_vmem: 2G
  tmem: 2G
  h_rt:  1:00:00
  submission_string: " "

trackplot:
  h_vmem: 10G
  tmem: 10G
  h_rt: 8:00:00
  submission_string: " "

combine_pdfs_within_dataset:
  h_vmem: 4G
  tmem: 4G
  h_rt:  1:00:00
  submission_string: " "
